---
- hosts: all
  gather_facts: yes
  connection: local

  vars:
    secret:
      - enable secret

  tasks:
  - name: "GET CONFIG"
    ios_command:
      commands:
        - "show running-config | include enable secret"
    register: get_config
    
  - name: RUN 'Find secret - Skip=compliant'
    when: "(get_config.stdout_lines[0][0] == '')"
    register: register_secret
    set_fact:
      var_secret: "false"
  
  - debug: var=var_secret
 
# Run Me: ansible-playbook -l 'R1' -i hosts -u admin -k -c local  playbooks/get_secret.yml
